version: '3'
services:
  # build with different context to be able to access server/schema.gql
  interface:
    build:
      context: .
      dockerfile: ./interface/Dockerfile
    ports: 
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_ENDPOINT
  server:
    build: ./server
    ports: 
      - "4000:4000"
    environment:
      - DATABASE_URI
    depends_on:
      - db
  db:
    image: postgres:15.0-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    volumes:
      - ./db-data/data:/var/lib/postgresql/data
      - ./server/initDB.sql:/docker-entrypoint-initdb.d/initDB.sql

